# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- redesign

pool:
  vmImage: 'windows-2019'

variables:
  testImgDir: 'FaceRecogTestFixtures'

stages:
- stage: BuildAndTestDebug
  displayName: BuildAndTestDebug
  jobs:  
  - job: 'Build'
    displayName: 'Build project'
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk 3.1'
        inputs:
          packageType: 'sdk'
          version: '3.1.101'
      - task: DotNetCoreCLI@2
        displayName: 'Restore packages'
        inputs:
          command: 'restore'
          projects: '**\*.csproj'
          feedsToUse: 'select'
      - task: VSBuild@1
        displayName: 'Build solution'
        inputs:
          solution: 'FaceRecog.sln'
          vsVersion: '16.0'
          platform: 'x64'
          configuration: 'Debug'
      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'FaceRecogTestFixtures.zip'
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: 'FaceRecogTestFixtures.zip'
          destinationFolder: '$(System.DefaultWorkingDirectory)'
          cleanDestinationFolder: false
      - task: VSTest@2
        displayName: 'Run unit ests'
        inputs:
          testImgDir: '$(System.DefaultWorkingDirectory)\$(testImgDir)'
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            Domain.UnitTests\**\*Tests.dll
            WorkTimeAlghorithm.UnitTests\**\*Tests.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
      - task: VSTest@2
        displayName: 'Run integration tests'
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            UnitTests\**\*Tests.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
