# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- redesign

pool:
  vmImage: 'windows-2019'

variables:
  testImgDir: '$(System.DefaultWorkingDirectory)\FaceRecogTestFixtures'

stages:
- stage: BuildAndTestDebug
  displayName: BuildAndTestDebug
  jobs:  
  - job: 'Build'
    displayName: 'Build project'
    steps:

      - task: DotNetCoreCLI@2
        displayName: 'Publish x64 Release version'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: 'Application\Application.csproj'
          arguments: '-c Release -r win-x64 -o AppRelease'
      - task: ZipAndDropBox@0
        inputs:
          sourceDir: '$(System.DefaultWorkingDirectory)\AppRelease'
          zipPath: 'Application.zip'
          dropboxtoken: '$(DropboxToken)'
